spring:
  application:
    name: kafka-sort-consume
server:
  port: 8080
kafka:
  server: 10.8.14.47:9092,10.8.14.47:9093,10.8.14.47:9094
  groupId: baiyan
  order:
    topic: baiyan-test
    concurrent: 3