server:
  port: 9001
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.8.14.84:30336/hero_all?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 9ZeNk0DghH


#TODO 1. tomcat 服务调优
#server.tomcat.uri-encoding: UTF-8
#server.tomcat.accept-count: 1000 # 等待队列最多允许1000个线程在队列中等待
#server.tomcat.max-connections: 20000 # 最大允许20000个链接被建立
## 最大工作线程数，默认200, 4核8g内存，线程数经验值800
#server.tomcat.threads.max: 1000 # 并发处理创建的最大的线程数量
#server.tomcat.threads.min-spare: 100 # 最大空闲连接数，防止突发流量


# 暴露所有的监控点
management.endpoints.web.exposure.include: '*'
# 定义Actuator访问路径
management.endpoints.web.base-path: /actuator
# 开启endpoint 关闭服务功能
management.endpoint.shutdown.enabled: true
